version: '3.8'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=laravel
      - MARIADB_DATABASE=laravel
      - MARIADB_PASSWORD=my_password
    container_name: mariadb

  myapp:
    tty: true
    image: docker.io/bitnami/laravel:8
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=laravel
      - DB_DATABASE=laravel
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
    ports:
      - 80:3000
    volumes:
      - ./:/app
    container_name: myapp
    # privileged: true # Privileged mode could be required to run this container under Windows
